# Generated by Django 3.2.12 on 2022-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='complaint',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
