# Generated by Django 3.2.12 on 2022-05-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20220525_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='leads.user'),
            preserve_default=False,
        ),
    ]
