# Generated by Django 3.2.12 on 2022-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_lead_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
    ]
