# Generated by Django 3.2.12 on 2022-05-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_remove_lead_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='username',
        ),
    ]
