# Generated by Django 3.2.12 on 2022-05-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_category_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='count',
            new_name='total_count',
        ),
    ]
