# Generated by Django 3.2.12 on 2022-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_rename_count_category_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.TextField()),
                ('sentiment_value', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='lead',
            name='complaint',
        ),
    ]
