# Generated by Django 3.2.12 on 2022-05-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_feedback_sentiment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_count',
            field=models.IntegerField(),
        ),
    ]
