# Generated by Django 3.2.12 on 2022-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_auto_20220526_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_value',
            field=models.IntegerField(null=True),
        ),
    ]
