# Generated by Django 3.2.12 on 2022-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_alter_feedback_sentiment_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment_value',
            field=models.IntegerField(default=-1),
        ),
    ]
