# Generated by Django 3.2.12 on 2022-06-12 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_alter_feedback_sentiment_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
